server:
  port: 8067
spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes: 
      - id: STUDENT-SERVICE
        uri:
           lb://STUDENT-SERVICE
        predicates:
        - Path=/student/**
        
      - id: COLLEGE-SERVICE
        uri:
           lb://COLLEGE-SERVICE
        predicates:
        - Path=/college/**
        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

        
   
